services:
  dns-tunnel-server:
    build:
      context: tunnels/iodine
      dockerfile: Dockerfile
    image: iodine
    container_name: dns-tunnel-server
    command: sh -c "iodined -f 10.0.0.1 test.com & (sleep 1 && socat tcp-listen:1080,fork,bind=10.0.0.1 tcp:172.22.0.6:1080)"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - '/dev/net/tun:/dev/net/tun'
    networks:
      experiment:
        ipv4_address: 172.22.0.2
    ports:
      - "53/udp"
      - "53/tcp"
    depends_on:
      - hev-socks5-server
      - cadvisor

  dns-tunnel-client:
    build:
      context: tunnels/iodine
      dockerfile: Dockerfile
    image: iodine
    container_name: dns-tunnel-client
    command: sh -c "iodine -f 172.22.0.2 test.com & (sleep 1 && socat tcp-listen:8000,fork,bind=172.22.0.3 tcp:10.0.0.1:1080)"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - '/dev/net/tun:/dev/net/tun'
    networks:
      experiment:
        ipv4_address: 172.22.0.3
    ports:
      - "8000/udp"
      - "8000/tcp"
    depends_on:
      - dns-tunnel-server
      - cadvisor
