services:
  dns-tunnel-server:
    build:
      context: tunnels/dnscat2
      dockerfile: Dockerfile.server
    image: dnscat2-server
    container_name: dns-tunnel-server
    command: 172.22.0.6
    restart: unless-stopped
    networks:
      experiment:
        ipv4_address: 172.22.0.3
    ports:
      - "8000/udp"
      - "8000/tcp"
    depends_on:
      - hev-socks5-server
      - cadvisor

  dns-tunnel-client:
    build:
      context: tunnels/dnscat2
      dockerfile: Dockerfile.client
    image: dnscat2-client
    container_name: dns-tunnel-client
    command: --dns domain=test.com,server=172.22.0.3,port=53
    restart: unless-stopped
    stop_grace_period: 1s
    networks:
      experiment:
        ipv4_address: 172.22.0.2
    ports:
      - "53/udp"
      - "53/tcp"
    depends_on:
      - dns-tunnel-server
      - cadvisor
