services:
  dns-tunnel-server:
    image: dns2tcp
    container_name: dns-tunnel-server
    command: dns2tcpd -F -d 1 -f /usr/src/app/.dns2tcpdrc
    restart: unless-stopped
    networks:
      experiment:
        ipv4_address: 172.22.0.2
    ports:
      - "53/udp"
      - "53/tcp"
    depends_on:
      - hev-socks5-server
      - cadvisor

  dns-tunnel-client:
    image: dns2tcp
    container_name: dns-tunnel-client
    command: sh -c "dns2tcpc -r socks -l 1080 -k key -z dns2tcp.hsc.fr 172.22.0.2 | (sleep 2 && socat tcp-listen:8000,fork tcp:127.0.0.1:1080)"
    restart: unless-stopped
    networks:
      experiment:
        ipv4_address: 172.22.0.3
    ports:
      - "8000/udp"
      - "8000/tcp"
    depends_on:
      - dns-tunnel-server
      - cadvisor
