---
- name: setup
  hosts: localhost
  collections:
    - community.docker
  
  tasks:
    - name: Set global variables
      set_fact:
        docker_network_name: "experiment"
    
    - block:
        - include_tasks: ../../experiment/tasks/docker-network.yml
        
        - include_tasks: ../../experiment/tasks/docker-socks.yml
        
        - include_tasks: ../../experiment/tasks/docker-iperf3.yml
        
        - include_tasks: ../../experiment/tasks/docker-big-files.yml
        
        - name: Build TUNS image
          community.docker.docker_image_build:
            name: tuns
            rebuild: always
            path: .
        
        - name: Run dns-tunnel-server
          community.docker.docker_container:
            name: dns-tunnel-server
            image: tuns
            restart_policy: unless-stopped
            command: sh -c "ruby tuns-server --debug -i 10.0.0.1 -t 10.0.0.2 -d test.com & (sleep 100 && socat tcp-listen:1080,fork,bind=10.0.0.1 tcp:172.22.0.6:1080)"
            capabilities:
              - NET_ADMIN
            devices:
              - '/dev/net/tun:/dev/net/tun'
            networks:
              - name: "{{ docker_network_name }}"
                ipv4_address: 172.22.0.2
            exposed_ports:
              - 53/udp
              - 53/tcp
        
        - name: Run dns-tunnel-client
          community.docker.docker_container:
            name: dns-tunnel-client
            image: tuns
            restart_policy: unless-stopped
            command: sh -c "ruby tuns-client --debug -i 10.0.0.2 -t 10.0.0.1 -n 172.22.0.2 -d test.com & (sleep 1 && socat tcp-listen:8000,fork,bind=172.22.0.3 tcp:10.0.0.1:1080)"
            capabilities:
              - NET_ADMIN
            devices:
              - '/dev/net/tun:/dev/net/tun'
            networks:
              - name: "{{ docker_network_name }}"
                ipv4_address: 172.22.0.3
            exposed_ports:
              - 8000/udp
              - 8000/tcp
        
        - include_tasks: ../../experiment/tasks/get-interface-name.yml
        
        - include_tasks: ../../experiment/tasks/tcpdump-setup.yml
        
        - import_tasks: ../../experiment/tasks/socks-client-download-files.yml
      
      always:
        - include_tasks: ../../experiment/tasks/tcpdump-destroy.yml
        
        - include_tasks: ../../experiment/tasks/docker-destroy.yml
