services:
  dns-tunnel-server:
    build:
      context: tunnels/dnstt
      dockerfile: Dockerfile
    image: dnstt
    container_name: dns-tunnel-server
    command: dnstt-server -udp :53 -privkey-file server.key t.example.com 172.22.0.6:1080
    restart: unless-stopped
    stop_grace_period: 1s
    networks:
      experiment:
        ipv4_address: 172.22.0.2
    ports:
      - "53/udp"
      - "53/tcp"
    depends_on:
      - hev-socks5-server
      - cadvisor

  dns-tunnel-client:
    build:
      context: tunnels/dnstt
      dockerfile: Dockerfile
    image: dnstt
    container_name: dns-tunnel-client
    command: dnstt-client -udp 172.22.0.2:53 -pubkey-file server.pub t.example.com 0.0.0.0:8000
    restart: unless-stopped
    networks:
      experiment:
        ipv4_address: 172.22.0.3
    ports:
      - "8000/udp"
      - "8000/tcp"
    depends_on:
      - dns-tunnel-server
      - cadvisor
