services:
  socks-server:
    image: heiher/hev-socks5-server:latest
    restart: unless-stopped
    networks:
      bridge:
        ipv4_address: 172.22.0.6
    expose:
      - "1080/tcp"
  dns-tunnel-server:
    image: dnstt
    pull_policy: never
    restart: always
    command: dnstt-server -udp :53 -privkey-file server.key t.example.com 172.22.0.6:1080
    stop_grace_period: 1s
    networks:
      bridge:
        ipv4_address: 172.22.0.2
    expose:
      - "53/udp"
      - "53/tcp"
  dns-tunnel-client:
    image: dnstt
    pull_policy: never
    restart: always
    command: dnstt-client -udp 172.22.0.2:53 -pubkey-file server.pub t.example.com 0.0.0.0:8000
    depends_on:
      - dns-tunnel-server
    networks:
      bridge:
        ipv4_address: 172.22.0.3
    expose:
      - "8000/udp"
      - "8000/tcp"
  iperf3-server:
    image: mlabbe/iperf3
    restart: unless-stopped
    healthcheck:
      disable: true
    networks:
      bridge:
        ipv4_address: 172.22.0.4
    expose:
      - "5201/udp"
      - "5201/tcp"
  socks-client:
    image: iperf3-hev-socks5-tunnel
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - '/dev/net/tun:/dev/net/tun'
    environment:
      - SOCKS5_ADDR=172.22.0.3
      - SOCKS5_PORT=8000
      - SOCKS5_UDP_MODE=tcp
      - IPV4_EXCLUDED_ROUTES=0.0.0.0/0
    networks:
      bridge:
        ipv4_address: 172.22.0.5
networks:
  bridge:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 172.22.0.0/16
